#!/usr/bin/env python3
"""Convert .vlw to a single PROGMEM-friendly C++ header."""
import os, glob

OUT = "/Users/justynroberts/work/cyd-death-clock/cyd-deathclock/include/fonts_outfit.h"

NAMES = {
    "outfit_bold_96.vlw":     "outfit_bold_96",
    "outfit_semibold_48.vlw": "outfit_semibold_48",
    "outfit_medium_22.vlw":   "outfit_medium_22",
    "outfit_regular_16.vlw":  "outfit_regular_16",
    "outfit_medium_12.vlw":   "outfit_medium_12",
}

def emit_array(symbol: str, data: bytes) -> str:
    lines = [
        f"// {symbol}: {len(data)} bytes",
        f"const uint8_t {symbol}[] PROGMEM = {{",
    ]
    # 16 bytes/line
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const uint32_t {symbol}_len = {len(data)};")
    lines.append("")
    return "\n".join(lines)

def main():
    base = os.path.dirname(os.path.abspath(__file__))
    out_lines = [
        "// fonts_outfit.h - generated by vlw_to_h.py from Outfit TTF",
        "// SIL Open Font License 1.1 (see Outfit project on GitHub)",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    total = 0
    for vlw, sym in NAMES.items():
        path = os.path.join(base, vlw)
        with open(path, "rb") as f:
            data = f.read()
        out_lines.append(emit_array(sym, data))
        total += len(data)
    out_lines.append(f"// total: {total} bytes")

    with open(OUT, "w") as f:
        f.write("\n".join(out_lines))
    print(f"Wrote {OUT} ({total} bytes of font data)")

if __name__ == "__main__":
    main()
